# Generated by Django 4.2.15 on 2024-08-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('abonement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_type', models.IntegerField()),
                ('duration_unit', models.IntegerField()),
                ('total_sessions', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_online', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('personal_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('has_subscription', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('subscription_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
